services:
  claims-api:
    container_name: data-claims-api-app
    profiles:
      - application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_SOURCE=internal
      secrets:
        - github_actor
        - github_token
    ports:
      - "8080:8080"
      - "8183:8081"
    environment:
      - AWS_REGION=us-east-1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/laa_data_claims_api_dev
      - AWS_ACCESS_KEY_ID=dummy-access-key
      - AWS_SECRET_ACCESS_KEY=dummy-access-key
      - AWS_ENDPOINT_URL=http://host.docker.internal:4566
      - AWS_SQS_ENDPOINT=http://host.docker.internal:4566
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laa_data_claims_api_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#  local AWS cloud stack for dev
#  localstack:
#    container_name: claims-api-sqs-localstack
#    image: localstack/localstack:latest
#    ports:
#      - "4566:4566"
#    environment:
#      - SERVICES=sqs
#      - DEBUG=1
#      - AWS_DEFAULT_REGION=us-east-1
#    volumes:
#      - "./docker-scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"

  audit-postgres:
    image: postgres:17
    container_name: local-audit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: javers_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - audit-postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  audit-postgres-data:

