resilience4j.ratelimiter:
  instances:
    submissionRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0
    claimRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0
    bulkSubmissionRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0
    matterStartRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0
    validationRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0
    assessmentRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 0