spring:
  datasource:
    url: ${DB_URL}
    username: "postgres"
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: ${HIKARI_MIN_POOL_SIZE}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
aws:
  region: ${AWS_REGION}
  sqs:
    endpoint: ""
    queue-name: ${QUEUE_NAME}
laa:
  springboot.starter:
    auth:
      authentication-header: "Authorization"
      authorized-clients: ${AUTHORIZED_CLIENTS}
      authorized-roles: ${AUTHORIZED_ROLES}
      unprotected-uris: ${UNPROTECTED_URIS}
    exports:
      enabled: true
      web:
        enabled: true
        base-path: /exports
      defaults:
        max-rows: 50000

resilience4j.ratelimiter:
  instances:
    submissionRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    claimRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    bulkSubmissionRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    matterStartRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    validationRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    assessmentRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
