spring:
  datasource:
    url: ${DB_URL}
    username: "postgres"
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: ${HIKARI_MIN_POOL_SIZE}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}

audit:
  datasource:
    url: ${AUDIT_DB_URL}
    username: "javers_user"
    password: ${AUDIT_DB_PASSWORD}
    hikari:
      minimum-idle: ${AUDIT_DB_HIKARI_MIN_POOL_SIZE}
      maximum-pool-size: ${AUDIT_DB_HIKARI_MAX_POOL_SIZE}
      idle-timeout: ${AUDIT_DB_HIKARI_IDLE_TIMEOUT}
      connection-timeout: ${AUDIT_DB_HIKARI_CONNECTION_TIMEOUT}

aws:
  region: ${AWS_REGION}
  sqs:
    endpoint: ""
    queue-name: ${QUEUE_NAME}
laa:
  springboot.starter.auth:
    authentication-header: "Authorization"
    authorized-clients: ${AUTHORIZED_CLIENTS}
    authorized-roles: ${AUTHORIZED_ROLES}
    unprotected-uris: ${UNPROTECTED_URIS}

resilience4j.ratelimiter:
  instances:
    submissionRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    claimRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    bulkSubmissionRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    matterStartRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    validationRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
    assessmentRateLimiter:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
