spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    placeholders:
      reporting_username: ${REPORTING_USERNAME}
      reporting_password: ${REPORTING_PASSWORD}
aws:
  region: ${AWS_REGION}
  sqs:
    endpoint: ""
    queue-name: ${QUEUE_NAME}
laa:
  springboot.starter.auth:
    authentication-header: "Authorization"
    authorized-clients: ${AUTHORIZED_CLIENTS}
    authorized-roles: ${AUTHORIZED_ROLES}
    unprotected-uris: ${UNPROTECTED_URIS}

resilience4j.ratelimiter:
  instances:
    submissionRateLimiter:
      limitForPeriod: 500
      limitRefreshPeriod: 1s
    claimRateLimiter:
      limitForPeriod: 500
      limitRefreshPeriod: 1s
    bulkSubmissionRateLimiter:
      limitForPeriod: 500
      limitRefreshPeriod: 1s
    matterStartRateLimiter:
      limitForPeriod: 500
      limitRefreshPeriod: 1s
    validationRateLimiter:
      limitForPeriod: 500
      limitRefreshPeriod: 1s