name: Deploy with Helm

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep-scan:
    name: semgrep-security-scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v6
      - name: Run Semgrep scan
        run: semgrep scan --exclude-rule python.django.security.django-no-csrf-token.django-no-csrf-token --error --config auto

  build-test:
    if: startsWith(github.head_ref || github.ref_name, 'openapi/') == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and test
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test coverage verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Integration test
        run: ./gradlew integrationTest --tests '*IntegrationTest'

      - name: Publish api models package
        run: |
          version=$(git rev-parse --short HEAD)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            version=${version}-SNAPSHOT
          fi
          ./gradlew :claims-data:api:publish -Pversion=$version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload service JAR artifact
        uses: actions/upload-artifact@v6
        with:
          name: service-jar
          path: claims-data/service/build/libs/*.jar
          retention-days: 1

      - name: Upload checkstyle report for claims-data
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: checkstyle-report
          path: claims-data/service/build/reports/checkstyle
          retention-days: 14

      - name: Upload test report for claims-data
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: claims-data/service/build/reports/tests
          retention-days: 14

      - name: Upload jacoco coverage report for claims-data
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-coverage-report
          path: claims-data/service/build/reports/jacoco
          retention-days: 14

  vulnerability-scan-app:
    runs-on: ubuntu-latest
    needs:
      - build-test
    permissions:
      contents: read
      security-events: write
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_TEST_EXCLUDE: build,generated
      SNYK_TARGET_REFERENCE: main
    steps:
      - uses: actions/checkout@v6

      - name: Run Snyk to check app for vulnerabilities
        uses: snyk/actions/gradle@master
        with:
          command: code test
          args: --severity-threshold=high

  vulnerability-scan-docker:
    runs-on: ubuntu-latest
    needs:
      - build-test
    permissions:
      contents: read
      security-events: write
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build app jar with gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build local Docker image
        run: |
          docker build -t claims-data-scan .
          docker save claims-data-scan -o image.tar

      - name: Run Snyk to scan Docker image from tarball
        uses: snyk/actions/docker@master
        with:
          image: image.tar
          args: --docker --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-push-docker:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs:
      - build-test
    permissions:
      id-token: write
      contents: read
    steps:

      - uses: actions/checkout@v6

      - name: Download JAR artifact
        uses: actions/download-artifact@v7
        with:
          name: service-jar
          path: claims-data/service/build/libs/

        # ---------- AWS auth (OIDC) ----------
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{  vars.ECR_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build and push a Docker image for claims-data
        run: |
          docker build --no-cache -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

  deploy-uat:
    runs-on: ubuntu-latest
    needs:
      - build-push-docker
      - vulnerability-scan-app
      - vulnerability-scan-docker
    environment: uat
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy UAT branch
        id: deploy_uat_branch
        uses: ./.github/actions/deploy_branch
        with:
          ecr-region: ${{ vars.ECR_REGION }}
          ecr-role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          app-environment: uat

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build-push-docker
      - vulnerability-scan-app
      - vulnerability-scan-docker
    environment: staging
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy staging
        id: deploy_staging
        uses: ./.github/actions/deploy
        with:
          ecr-region: ${{ vars.ECR_REGION }}
          ecr-role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          app-environment: staging

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy production
        id: deploy_production
        uses: ./.github/actions/deploy
        with:
          ecr-region: ${{ vars.ECR_REGION }}
          ecr-role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          app-environment: production
